export const INCREMENT = 'INCREMENT';
export const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
export const DECREMENT = 'DECREMENT';

export const GET_LIST_POKEMON_REQUEST = 'GET_LIST_POKEMON_REQUEST';
export const GET_LIST_POKEMON_SUCCESS = 'GET_LIST_POKEMON_SUCCESS';
export const GET_LIST_POKEMON_FAIL = 'GET_LIST_POKEMON_FAIL';
